server:
  port: 8080

spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@  # 当前激活配置，默认dev
  # Spring Boot Admin
  boot:
    admin:
      client:
        url: http://ballcat-monitor:9999
        username: admin
        password: 123456
        # 优先使用 ip 访问 client 端
        instance:
          service-host-type: ip
  messages:
    # basename 中的 . 和 / 都可以用来表示文件层级，默认的 basename 是 messages
    basename: 'ballcat-*, org.springframework.security.messages, i18n.messages, i18n/attributes'
#  mvc:
#    pathmatch:
#      matching-strategy: ant-path-matcher

# Spring Boot Actuator 暴露监控端口
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 图形验证码
aj:
  captcha:
    waterMark: 'BallCat'
    cacheType: redis
    
# 天爱图形验证码
captcha:
  secondary:
    enabled: true

# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      logic-delete-value: "NOW()" # 逻辑已删除值(使用当前时间标识)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


# 定时任务相关配置
xxl:
  job:
    admin:
      addresses: http://ballcat-job:8888/xxl-job-admin # xxl-job-admin 接口地址
    executor:
      port: 8081 #通讯端口
      appName: ballcat-admin-jobs
      logretentiondays: 30 #日志保留天数


# BallCat 相关配置
ballcat:
  system:
    password-rule: ^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d()`~!@#$%^&*-_+=|{}\[\]:;'<>,.?/]{6,16}$
  websocket:
    message-distributor: redis
  security:
    # 前端传输密码的 AES 加密密钥
    password-secret-key: '==BallCat-Auth=='
    oauth2:
      authorizationserver:
        # 登陆验证码是否开启
        login-captcha-enabled: true
      resourceserver:
        ## 忽略鉴权的 url 列表
        ignore-urls:
          - /public/**
          - /actuator/**
          - /doc.html
          - /v2/api-docs/**
          - /v3/api-docs/**
          - /swagger-resources/**
          - /swagger-ui/**
          - /swagger-ui.html
          - /webjars/**
          - /bycdao-ui/**
          - /favicon.ico
          - /captcha/**
  # 项目 redis 缓存的 key 前缀
  redis:
    key-prefix: 'ballcat:'
  # actuator 加解密密钥
  actuator:
    auth: true
    secret-id: 'ballcat-monitor'
    secret-key: '=BallCat-Monitor'
  openapi:
    info:
      title: BallCat-Admin Docs
      description: BallCat 后台管理服务Api文档
      version: ${project.version}
      terms-of-service: http://www.ballcat.cn/
      license:
        name: Powered By BallCat
        url: http://www.ballcat.cn/
      contact:
        name: Hccake
        email: chengbohua@foxmail.com
        url: https://github.com/Hccake
    components:
      security-schemes:
        apiKey:
          type: APIKEY
          in: HEADER
          name: 'api-key'
        oauth2:
          type: OAUTH2
          flows:
            password:
              token-url: /oauth/token
    security:
      - oauth2: []
      - apiKey: []


springdoc:
  swagger-ui:
    oauth:
      client-id: test
      client-secret: test
    display-request-duration: true
    disable-swagger-default-url: true
    persist-authorization: true